"""empty message

Revision ID: c0988b3c7b44
Revises: 
Create Date: 2022-09-23 13:25:41.170642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0988b3c7b44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('serial', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('ptz', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('serial', name='modules_pkey')
    )
    # ### end Alembic commands ###
