version: '3.8'

services:
  web:
    image: mydjango
    command: python manage.py runserver 0.0.0.0:8000 &
# Uncomment if debug
#    volumes:
#      - ./portfolio/portfolio:/usr/src/app/portfolio
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev